DROP DATABASE IF EXISTS guessGame;
CREATE DATABASE guessGame;

CREATE TABLE Game(
gameId INT PRIMARY KEY,
answer VARCHAR(20) NOT NULL,
guessesUsed INT NOT NULL,
difficulty VARCHAR(10) NOT NULL,
gameWon BOOLEAN DEFAULT false NOT NULL);
