DROP DATABASE IF EXISTS Blog;
CREATE DATABASE Blog;

USE Blog;

CREATE TABLE Post (
 postID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
 title VARCHAR(100) NOT NULL,
 blogPost longtext NOT NULL,
 blogDate DATE NOT NULL
);
